import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#37333e',
        'inverse-primary': '#732ee4',
        secondary: '#adc6ff',
        surface: '#15121b',
        'surface-container': '#221e28',
        tertiary: '#ffb784',
        'on-surface-variant': '#ccc3d8',
        'tertiary-fixed-dim': '#ffb784',
        'surface-tint': '#d2bbff',
        'tertiary-container': '#a15100',
        'secondary-fixed': '#d8e2ff',
        'on-primary': '#3f008e',
        'on-background': '#e8dfee',
        primary: '#d2bbff',
        'on-tertiary-fixed': '#301400',
        'on-secondary-fixed-variant': '#004395',
        'secondary-fixed-dim': '#adc6ff',
        'error-container': '#93000a',
        'outline-variant': '#4a4455',
        error: '#ffb4ab',
        'on-surface': '#e8dfee',
        'surface-container-low': '#1d1a24',
        outline: '#958da1',
        'on-primary-container': '#ede0ff',
        'on-primary-fixed-variant': '#5a00c6',
        'surface-container-lowest': '#100d16',
        'on-tertiary-fixed-variant': '#713700',
        'inverse-on-surface': '#332f39',
        'tertiary-fixed': '#ffdcc6',
        'surface-variant': '#37333e',
        'secondary-container': '#0566d9',
        'surface-container-high': '#2c2833',
        'surface-dim': '#15121b',
        'on-tertiary-container': '#ffe0cd',
        background: '#15121b',
        'surface-bright': '#3c3742',
        'on-primary-fixed': '#25005a',
        'on-secondary-fixed': '#001a42',
        'inverse-surface': '#e8dfee',
        'on-tertiary': '#4f2500',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#d2bbff',
        'on-secondary-container': '#e6ecff',
        'on-error': '#690005',
        'primary-fixed': '#eaddff',
        'primary-container': '#7c3aed',
        'on-secondary': '#002e6a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-gap': '160px',
        gutter: '24px',
        margin: '32px',
        'container-max': '1200px',
        unit: '8px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'display-xl': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}

export default config
